# Generated by Django 2.0.1 on 2018-04-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('precipitable_water', models.FloatField(blank=True, db_column='Precipitable_water_entire_atmosphere_single_layer', null=True)),
                ('pressure_surface', models.FloatField(blank=True, db_column='Pressure_surface', null=True)),
                ('relative_humidity', models.FloatField(blank=True, db_column='Relative_humidity_isobaric', null=True)),
                ('temperature_surface', models.FloatField(blank=True, db_column='Temperature_surface', null=True)),
                ('wind_speed', models.FloatField(blank=True, db_column='Wind_speed_gust_surface', null=True)),
                ('solar_zenith', models.FloatField(blank=True, db_column='solar zenith', null=True)),
                ('ghi', models.FloatField(blank=True, db_column='GHI', null=True)),
                ('time', models.DateTimeField(blank=True, db_column='Time', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'data',
            },
        ),
    ]
